### PR TITLE
feat: add LOGISTRATION_MINIMAL_HEADER env variable

### PR DESCRIPTION
**Pull request by waheedahmed**
The `LOGISTRATION_MINIMAL_HEADER` environment variable removes the main menu links from the header. It also removes login/register links from the menu if user is unauthenticated.

### CODE REVIEW

**Comment by waheedahmed** [comment]
@davidjoy Do we also need to do this in [@edx/frontend-component-header-edx](https://github.com/edx/frontend-component-header-edx) or the logo is configurable in this component so that we can change it edX logo when we go live?

I know there is a similar env variable (`MINIMAL_HEADER`) available in that component as well but that does not hide the login/register links from the header and does not serve our purpose completely.

**Comment by davidjoy** [comment]
The @edx/frontend-component-header-edx is what actually gets used on edx.org - this repository does not get used in production.  I'd suggest adding this variable in that repo and leaving this one as-is.

**Comment by waheedahmed** [comment]
@davidjoy I believe we need this in both to keep the user experience same for the edX and OpenedX community. I'll make a PR for @edx/frontend-component-header-edx as well.

**Comment by waheedahmed** [comment]
Created PR for edX specific header component as well https://github.com/edx/frontend-component-header-edx/pull/105.

**Review by zainab-amir — APPROVED** [review]

**Pull request merged**
